name = "NUSFSpectra"
uuid = "9fbcb602-ec67-11e8-3dec-f59abf6c190e"
authors = ["MLackner <lacknersmichael@gmail.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
